name: User Profile
description: User Profile
icon: user
table: mein_user_profile
show_admin_menu: false
parent_menu: null
menu_position: null
fields:
  gender:
    field: gender
    label: Jenis Kelamin
    form: radio
    options:
      l: Laki-laki
      p: Perempuan
    default: l
  birthday:
    field: birthday
    label: Tanggal Lahir
    form: date
  status_marital:
    field: status_marital
    label: Status Marital
    form: dropdown
    options:
      single: single
      nikah: Menikah
      duda: Duda/Janda
    default: single
  address:
    field: address
    label: Alamat Lengkap
    form: textarea
  city:
    field: city
    label: Kota/Kabupaten
    form: text
  jobs:
    field: jobs
    label: Pekerjaan
    form: text
  record_log:
    field: record_log
    label: Record Log
    form: switch
    admin_only: true
    options:
      0: No
      1: Yes
    default: 0
  akun_ig:
    field: akun_ig
    label: Akun Instagram
    form: text
  akun_tiktok:
    field: akun_tiktok
    label: Akun TikTok
    form: text
  hobi:
    field: hobi
    label: Hobi
    form: Text
  nomor_rekening:
    field: nomor_rekening
    label: Nomor Rekening
    description: Nomor Rekening untuk menerima pencairan komisi
    form: text
  bank:
    field: bank
    label: Nama Bank
    form: text
  pemilik_rekening:
    field: pemilik_rekening
    label: Nama Pemilik Rekening
    form: text
