name: Activity Log
description: Log user activity
icon: list
table: activity_logs
disable_add: true
show_admin_menu: true
parent_menu: "90:Configurations:cog"
menu_position: 18
soft_deletes: true
hide_edit: true
disable_delete: true
show_on_table: [module,action,user_id,user_agent,post_data,created_at]
fields:
  module:
    field: module
    label: Module
    form: text
  action:
    field: action
    label: Action
    form: textarea
  post_data:
    field: post_data
    label: POST Data
    form: json
  user_agent:
    field: user_agent
    label: User Agent
    form: textarea
  user_id:
    field: user_id
    label: User
    form: dropdown
    relation:
      entry: user
      caption: name
      model: User_model
      model_path: user/User_model
  created_at:
    field: created_at
    label: Created At
    form: datetime
