name: Data Downloader
description: Custom data downloader
icon: download
table: mein_exporter
parent_menu: "90:Configurations:cog"
menu_position: 100
show_admin_menu: true
show_on_table: [title,description]
fields:
  title:
    field: title
    label: Title
    form: text
    rules: required
  slug:
    field: slug
    label: Slug
    form: slug
    rules: required
    referer: title
  description:
    field: description
    label: Description
    form: textarea
  query:
    field: query
    label: Query
    form: code
    fullwidth: true
    mode: sql
action_buttons:
  row:
    preview: 
      caption: Preview data
      icon: search
      target: _blank
    download: 
      caption: Download data
      icon: download