name: "tests build"

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  build:
    name: PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.1', '8.2']
    steps:
      - name: Setup PHP Action
        uses: shivammathur/setup-php@v2
        with:
          extensions: intl
          php-version: "${{ matrix.php-versions }}"
          coverage: xdebug
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Validate composer.json"
        run: "composer validate"
      - name: "Install dependencies"
        run: "composer install"
      - name: "CS Check"
        run: "vendor/bin/php-cs-fixer fix --dry-run --diff"
      - name: "Code analyze"
        run: |
          vendor/bin/phpstan
          vendor/bin/rector process --dry-run
      - name: "Run test suite"
        run: "vendor/bin/phpunit"
